version: "3"
services:
  frontend:
    image: react-app
    build: ./front-end 
    container_name: front-end
    stdin_open : true
    # ports: 
    #   - "3000:3000" 
    restart: always 
    links:
      - backend
    depends_on:
      - backend
    networks:
      - linkednyunetwork

  backend:
    image: server-app
    build: ./back-end
    container_name: back-end
    # ports:
    #   - "5000:5000"
    restart: always
    networks:
      - linkednyunetwork

  nginx:
    restart: always
    depends_on:
      - frontend
      - backend
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - 3000:80
    networks:
      - linkednyunetwork

networks:
  linkednyunetwork:
    driver: bridge