version: "3"
services:
  frontend:
    image: react-app
    build: ./front-end 
    stdin_open : true
    ports: 
      - "3000:3000" 
    restart: always 
    links:
      - backend
    depends_on:
      - backend
    networks:
      - linkednyunetwork

  backend:
    image: server-app
    build: ./back-end
    ports:
      - "5000:5000"
    restart: always
    networks:
      - linkednyunetwork

networks:
  linkednyunetwork:
    driver: bridge