version: "3"
services:
  frontend:
    image: react-app
    build: ./front-end 
    container_name: front-end
    stdin_open : true 
    restart: always 
    links:
      - backend
    depends_on:
      - backend
    networks:
      - linkednyunetwork

  backend:
    image: server-app
    build: ./back-end
    container_name: back-end
    restart: always
    networks:
      - linkednyunetwork

  nginx:
    image: linuxserver/swag
    restart: always
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/config:/config
      - ./nginx/default.conf:/config/nginx/site-confs/default
      - ./nginx/ssl.conf:/config/nginx/ssl.conf
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    networks:
      - linkednyunetwork
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=linkednyu.com
      - SUBDOMAINS=www,
      - VALIDATION=http
      - STAGING= false 
      - EMAIL=pla252@nyu.edu

networks:
  linkednyunetwork:
    driver: bridge